# Generated by Django 5.0.1 on 2024-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='description',
        ),
        migrations.AlterField(
            model_name='storage',
            name='technology',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('M.2', 'M.2')], max_length=3),
        ),
    ]
