# Generated by Django 5.0.1 on 2024-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
