# Generated by Django 5.0.1 on 2024-05-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_ram_description_remove_ram_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphiccard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='description',
        ),
        migrations.AlterField(
            model_name='screen',
            name='inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='refreshrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='technology',
            field=models.CharField(choices=[('LED', 'LED'), ('LCD', 'LCD'), ('OLED', 'OLED')], max_length=4),
        ),
        migrations.AlterField(
            model_name='storage',
            name='capacity',
            field=models.IntegerField(default=520),
        ),
    ]
