# Generated by Django 5.0.1 on 2024-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_graphiccard_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/products'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='speed',
            field=models.FloatField(),
        ),
    ]
