# Generated by Django 5.0.1 on 2024-05-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_payment_amount_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
    ]
