# Generated by Django 5.0.1 on 2024-05-27 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.recipe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.recipe'),
        ),
    ]
