# Generated by Django 5.0.1 on 2024-06-06 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_payment_date_paid_alter_delivery_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
