# Generated by Django 5.0.1 on 2024-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='run',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
